

## Machine Learning 
### TP n°1 (Scientific computing with NumPy)
### 2022-2023

---


**<code>Importing the NumPy library </code>**


In [1]:
import numpy as np

###**<code>A- </code>**

**1.** Create an ndarray, named `M` , of size `4×4` containing integers from 0 to 15 . Display `M`.



In [2]:
M = np.arange(16).reshape(4,4)
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

**2.** Display the 2nd row of `M` , then display its last element. 


In [3]:
print(M[1])
print(M[3][3])

[4 5 6 7]
15


**3.** Display the elements of the diagonal of `M`.

In [4]:
for i in range(4):
  print(M[i][i])

0
5
10
15


**4.** Create an array `ndarray` `M1` that represents the result of transposing the last two columns of `M`. 


In [5]:
A = M[:,2:4]
M1 = A.transpose()
print(M1)

[[ 2  6 10 14]
 [ 3  7 11 15]]


**5.** Swap the two rows of `M1` . Display `M1` 

In [6]:
M1[[0,1]] = M1[[1,0]]
print(M1)

[[ 3  7 11 15]
 [ 2  6 10 14]]


###**<code>B- </code>**


**1.** Create an array of dimension 1 , named `vect` , with 12 random elements between 0 and 20 . Display `vect`.


In [7]:
vect = np.random.randint(20, size=(12))
print(vect)

[ 8  4 14 11 10  1  4  2  8 13 18  8]


**2.** Transform `vect` into a two-dimensional (2D) array, named `t_b` , of 4 rows and 3 columns. Display `t_b`.


In [8]:
t_b = np.array(vect).reshape(4, 3)
print(t_b)

[[ 8  4 14]
 [11 10  1]
 [ 4  2  8]
 [13 18  8]]


**3.** Display the size, dimension and number of elements of `t_b`.
 

In [9]:
print(np.shape(t_b))

(4, 3)


**4.** Display the maximum of each row of `t_b`.


In [10]:
for i in range(4):
  print("max of row",i+1,"is",np.max(t_b[i]))

max of row 1 is 14
max of row 2 is 11
max of row 3 is 8
max of row 4 is 18


**5.** Display the sum of each column of `t_b`.


In [11]:
for i in range(3):
  print(np.sum(t_b[:,i]))

36
34
31


**6.** Transform `t_b` into an array of size 4×4 , named `t_a` . Display `t_a`.


In [60]:
t_a = np.resize(t_b,16).reshape(4, 4)
print(t_a)

[[ 8  4 14 11]
 [10  1  4  2]
 [ 8 13 18  8]
 [ 8  4 14 11]]


**7.** Decompose `t_a` vertically into 4 arrays `X` , `Y` , `Z` and `T` with 4 elements each.


In [59]:
X = t_a[:,0]
Y = t_a[:,1]
Z = t_a[:,2]
T = t_a[:,3]
print(X,Y,Z,T)

[ 8 10  8  8] [ 4  1 13  4] [14  4 18 14] [11  2  8 11]


**8.** Merge the array `X` and `t_a` so that the rows of `X` are added as a new column to `t_a`.


In [61]:
t_a = np.hstack((t_a,X.reshape((4,1))))
print(t_a)

[[ 8  4 14 11  8]
 [10  1  4  2 10]
 [ 8 13 18  8  8]
 [ 8  4 14 11  8]]


**9.** Define an array `t_u` of dimension 1 containing the elements of `t_a` sorted in ascending order so that no element is duplicated. Display `t_u`.


In [76]:

t_u = [t_a[i][j] for i in range(len(t_a)) for j in range(len(t_a[0]))]
t_u.sort()
print(t_u)


[1, 2, 4, 4, 4, 8, 8, 8, 8, 8, 8, 8, 10, 10, 11, 11, 13, 14, 14, 18]


**10.** Transform `t_u` into an array of size `4×3` . Then insert the elements of `Y` in the second column of `t_u` . Display `t_u`.


In [81]:
t_u = np.resize(t_u,12).reshape(4,3)
t_u = np.hstack((t_u,Y.reshape(4,1)))
print(t_u)

[[ 1  2  4  4]
 [ 4  4  8  1]
 [ 8  8  8 13]
 [ 8  8  8  4]]


**11.** Shuffle the elements of the second row of `t_u` . Display `t_u` and the position of its largest element as a tuple `(row, column)`.

In [84]:
np.random.shuffle(t_u[1])
print(t_u)

[[ 1  2  4  4]
 [ 1  4  8  4]
 [ 8  8  8 13]
 [ 8  8  8  4]]


In [92]:
print(np.argmax(t_u))

11


In [89]:
rslt = t_u[0][0]
for i in range(len(t_u)):
  for j in range(1,len(t_u[0])):
    if rslt < t_u[i][j] :
      rslt = t_u[i][j]
      l = i+1
      k = j+1
print("(",l,",",k,")")

( 3 , 4 )
